[workspace]
members = [
    # 邮件服务

    "capricorn-email",
    "capricorn-ml",
    #实时通信系统
    "capricorn-rtc",
    #统一用户认证
    # "capricorn-identity",
    # 定义使用的rpc
    # "capricorn-rpc",
    # 短信
    # "capricorn-sms",
    #共用工具
    # "capricorn-tools",
    # 主程序
    "capricorn-web",
]