[package]
name = "capricorn-web"
version = "0.1.0"
authors = ["walker <warriorsfly@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix = "0.10"
actix-cors = "0.4"
actix-web = "3"
actix-web-actors = "3"
actix-files = "0.4"
actix-codec = "0.3"
actix-redis = {version="0.9",optional = true}
rand = "0.7"
redis-async = { version = "0.6", optional = true }
bytes = "0.5"
byteorder = "1"

derive_more = "0.99"
dotenv = "0.15"
envy = "0.4"
# env_logger = "0.7"
futures = "0.3"
# jsonwebtoken = "7"
lazy_static = "1"
serde = "1"
serde_derive = "1"
serde_json = "1"

[dev-dependencies]
actix-rt = "1"

# [features]
# default = ["extras"]
# extras=["redis"]
# # use redis or not
# redis=["actix-redis","redis-async"]
