[package]
name = "capricorn-web"
version = "0.1.0"
authors = ["walker <warriorsfly@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix = "0.10"
actix-cors = "0.5"
actix-web = "3"
actix-web-actors = "3"
actix-files = "0.4"
actix-codec = "0.3"
async-graphql = "2"
async-graphql-actix-web = "2"
rand = "0.7"
# redis-async = { version = "0.7", optional = true }
bytes = "0.6"
byteorder = "1"

derive_more = "0.99"
dotenv = "0.15"
envy = "0.4"
# env_logger = "0.7"
futures = "0.3"
# jsonwebtoken = "7"
lazy_static = "1"
serde = "1"
serde_derive = "1"
serde_json = "1"

[dependencies.sqlx]
version = "0.4.0-beta.1"
default-features = false
features = [ "macros", "runtime-actix", "postgres", "migrate", "json", "chrono", "uuid" ]

[dev-dependencies]
actix-rt = "1"